import React from "react";
import ArrowSVG from './SVG/arrow-down.svg'
import {useEffect, useState} from 'react'
import './css/terminos.css'
import './css/index.css'

export default function Terms(){

      const [cookie, setCookie] = useState()
      const [lenguague, setLenguague] = useState('es')
    
      useEffect(() => {
        setCookie(JSON.parse(localStorage.getItem("terms")))
        localStorage.setItem('lenguague', JSON.stringify('es'))
        setLenguague(JSON.parse(localStorage.getItem("lenguague")))
      },[cookie])
      
      const selectLenguague = (leng)=> {
        localStorage.setItem('lenguague', JSON.stringify(leng)) 
        setLenguague(JSON.parse(localStorage.getItem("lenguague")))
      }

    return(
        <div id="terminos">
            <section className="terminos_condiciones">
                    <ul className="drop">
                        <li className="dropdown">
                            <button className="dropdown-btn">
                                <img src={ArrowSVG} width="10px" alt="icon-arrow"/>
                                {lenguague === 'es'?"Lenguaje": "Lenguague"}
                            </button>  
                            <div className="dropdown-content">
                                <button onClick={selectLenguague}>{lenguague === 'es'?"Español":"Spanish"}</button>
                                <button onClick={selectLenguague}>{lenguague === 'es'?"Inglés":"English"}</button>
                            </div>
                        </li>
                    </ul>
                    <h1>{lenguague==='es'?"Terminos y condiciones":"Terms and Conditions"}</h1>
                    <p>{lenguague==='es'?"Esta página web es propiedad y está operado por Serafin Martínez Martínez. Estos Términos establecen los términos y condiciones bajo los cuales tu puedes usar nuestra página web y servicios ofrecidos por nosotros. Esta página web ofrece a los visitantes servicios de mantenimiento y limpieza de jardinería. Al acceder o usar la página web de nuestro servicio, usted aprueba que haya leído, entendido y aceptado estar sujeto a estos Términos:":"This website is owned and operated by Serafin Martínez Martínez. These Terms establish the terms and conditions under which you can use our website and services offered by us. This website offers visitors garden maintenance and cleaning services. By accessing or using the website of our service, you agree that you have read, understood and agreed to be bound by these Terms:"}</p>
                    <ul>
                        <li>
                            <p>{lenguague ==='es'?"Los datos proporcionados por nuestros usuarios seran privados y en ningun caso expuestos con otras empresas o servicios similares. Los datos proporcionados en esta página web seran utilizados solamente para comunicarnos con nuestros clientes y ofrecer la mejor experiencia posible sobre nuestros servicios.":"The data provided by our users will be private and in no case exposed with other companies or similar services. The data provided on this website will be used only to communicate with our customers and offer the best possible experience on our services."}</p>
                        </li>
                        <li>
                            <p>{lenguague ==='es'?"Para usar nuestro página web y / o recibir nuestros servicios, debes tener al menos 21 años de edad, o la mayoría de edad legal en tu jurisdicción, y poseer la autoridad legal, el derecho y la libertad para participar en estos Términos como un acuerdo vinculante. No tienes permitido utilizar esta página web y / o recibir servicios si hacerlo está prohibido en tu país o en virtud de cualquier ley o regulación aplicable a tu caso.":"To use our website and / or receive our services, you must have at least 21 years of age, or the legal age of majority in your jurisdiction, and possess the legal authority, right, and freedom to enter these Terms as a binding agreement. You are not allowed to use this website and / or receive services if doing so is prohibited in your country or under any law or regulation applicable to your case."}</p>  
                        </li>
                        <li>
                            <p>{lenguague ==='es'?"El Servicio y todos los materiales incluidos o transferidos, incluyendo, sin limitación, software, imágenes, texto, gráficos, logotipos, patentes, marcas registradas, marcas de servicio, derechos de autor, fotografías, audio, videos, música y todos los Derechos de Propiedad Intelectual relacionados con ellos, son la propiedad exclusiva de [Nombre del propietario dela página web]. Salvo que se indique explícitamente en este documento, no se considerará que nada en estos Términos crea una licencia en o bajo ninguno de dichos Derechos de Propiedad Intelectual, y tu aceptas no vender, licenciar, alquilar, modificar, distribuir, copiar, reproducir, transmitir, exhibir públicamente, realizar públicamente, publicar, adaptar, editar o crear trabajos derivados de los mismos.":"The Service and all materials included or transferred, including without limitation limitation, software, images, text, graphics, logos, patents, trademarks, service marks, copyrights, photographs, audio, videos, music and all Intellectual Property Rights related to them, are the exclusive property of Safarin Martínez Martinez. Except as explicitly stated in this document, nothing in these Terms shall be deemed to create a license in or under any such Intellectual Property Rights, and you agree not to sell, license, rent, modify, distribute, copy, reproduce, transmit , publicly display, publicly perform, publish, adapt, edit or create derivative works thereof."}</p>
                        </li>
                        <li>
                            <p>{lenguague ==='es'?"Usted acuerda indemnizar y eximir de responsabilidad a Serafin Martínez Martínez de cualquier demanda, pérdida, responsabilidad, reclamación o gasto (incluidos los honorarios de abogados) que terceros realicen en tu contra como consecuencia de, o derivado de, o en relación con tu uso de la página web o cualquiera de los servicios ofrecidos en la página web.":"You agree to indemnify and hold Serafin Martínez Martínez harmless of any lawsuit, loss, liability, claim or expense (including legal fees) that third parties make against you as a result of, or derived from, or in relation to your use of the website or any of the services offered on the Web page."}</p>
                        </li>
                        <li>
                            <p>{lenguague ==='es'?"Nos reservamos el derecho de modificar estos términos de vez en cuando a nuestra entera discreción. Por lo tanto, debes revisar estas páginas periódicamente. Cuando cambiemos los Términos de una manera material, te notificaremos que se han realizado cambios importantes en los Términos. El uso continuado de la página web o nuestro servicio después de dicho cambio constituye tu aceptación de los nuevos Términos. Si no aceptas alguno de estos términos o cualquier versión futura de los Términos, no uses o accedas (o continúes accediendo) a la página web o al servicio.":"We reserve the right to modify these terms from time to time at our sole discretion. Therefore, you should review these pages periodically. When we change the Terms in a material way, we will notify you that material changes have been made to the Terms. Your continued use of the website or our service after such change constitutes your acceptance of the new Terms. If you do not accept any of these terms or any future version of the Terms, do not use or access (or continue to access) the website or service."}</p>
                        </li>
                        <li>
                            <p>{lenguague ==='es'?"Acepta recibir de vez en cuando nuestros mensajes y materiales de promoción, por correo postal, correo electrónico o cualquier otro formulario de contacto que nos proporciones (incluido tu número de teléfono para llamadas o mensajes de texto). Si no deseas recibir dichos materiales o avisos de promociones, simplemente avísanos en cualquier momento.":"You agree to receive our messages and promotional materials from time to time, by postal mail, email or any other contact form that you provide us (including your phone number for calls or text messages). If you do not wish to receive such promotional materials or notices, simply let us know at any time."}</p>
                        </li>
                        <li>
                            <p>{lenguague ==='es'?"Si tiene duda sobre los terminos y condiciones, puede contactarnos por medio de el correo jaredslandscape.maintenance@gmail.com.":"If you have questions about the terms and conditions, you can contact us through email jaredslandscape.maintenance@gmail.com."}</p>
                        </li>
                    </ul>

                    <h2>{lenguague==='es'?"Política de Cookies":"Cookies policy"}</h2>
                    <p>{lenguague==='es'?"En esta web se utilizan cookies de terceros y propias para conseguir que tengas una mejor experiencia de navegación, puedas compartir contenido en redes sociales y para que podamos obtener estadísticas de los usuarios. Puedes evitar la descarga de cookies a través de la configuración de tu navegador, evitando que las cookies se almacenen en su dispositivo. Como propietario de este sitio web, te comunico que no utilizamos ninguna información personal procedente de cookies, tan sólo realizamos estadísticas generales de visitas que no suponen ninguna información personal. Es muy importante que leas la presente política de cookies y comprendas que, si continúas navegando, consideraremos que aceptas su uso.Según los términos incluidos en el artículo 22.2 de la Ley 34/2002 de Servicios de la Sociedad de la Información y Comercio Electrónico, si continúas navegando, estarás prestando tu consentimiento para el empleo de los referidos mecanismos.":"On this website, third-party and own cookies are used to ensure that you have a better browsing experience, you can share content on social networks and so that we can obtain user statistics. You can prevent the download of cookies through your browser settings, preventing cookies from being stored on your device. As the owner of this website, I inform you that we do not use any personal information from cookies, we only carry out general statistics of visits that do not imply any personal information. It is very important that you read this cookie policy and understand that if you continue browsing, we will consider that you accept its use. According to the terms included in article 22.2 of Law 34/2002 on Services of the Information Society and Electronic Commerce, if you continue browsing, you will be giving your consent for the use of the aforementioned mechanisms."}</p>
                    <ul>
                        <li>
                            <h3>{lenguague === 'es'?"Entidad Responsable":"Responsible Entity"}</h3>
                            <p>{lenguague==='es'?"La entidad responsable de la recogida, procesamiento y utilización de tus datos personales, en el sentido establecido por la Ley de Protección de Datos Personales es la página http://www.jareds-landscape-maintenance.com/, propiedad de Serafin Martínez Martínez – Estados Unidos Oregon.":"The entity responsible for the collection, processing and use of your personal data, in the sense established by the Law on Protection of Personal Data is the page http://www.jareds-landscape-maintenance.com/, owned by Sefarin Martínez Martínez - United States Oregon."}</p>
                        </li>
                        <li>
                            <h3>{lenguague === 'es'?"¿Qué son las cookies?":"What are cookies?"}</h3>
                            <p>{lenguague==='es'?"Las cookies son un conjunto de datos que un servidor deposita en el navegador del usuario para recoger la información de registro estándar de Internet y la información del comportamiento de los visitantes en un sitio web. Es decir, se trata de pequeños archivos de texto que quedan almacenados en el disco duro del ordenador y que sirven para identificar al usuario cuando se conecta nuevamente al sitio web. Su objetivo es registrar la visita del usuario y guardar cierta información. Su uso es común y frecuente en la web ya que permite a las páginas funcionar de manera más eficiente y conseguir una mayor personalización y análisis sobre el comportamiento del usuario":"Cookies are a set of data that a server deposits in the user's browser to collect standard Internet registration information and information on the behavior of visitors to a website. In other words, these are small text files that are stored on the computer's hard drive and that serve to identify the user when they connect to the website again. Its purpose is to record the user's visit and save certain information. Its use is common and frequent on the web since it allows the pages to function more efficiently and achieve greater personalization and analysis of user behavior."}</p>
                        </li>
                        <li>
                            <h3>{lenguague==='es'?"¿Qué tipos de cookies existen?":"What types of cookies are there?"}</h3>
                            <p>{lenguague==='es'?"Las cookies utilizadas en nuestro sitio web, son de sesión y de terceros, y nos permiten almacenar y acceder a información relativa al idioma, el tipo de navegador utilizado, y otras características generales predefinidas por el usuario, así como, seguir y analizar la actividad que lleva a cabo, con el objeto de introducir mejoras y prestar nuestros servicios de una manera más eficiente y personalizada.Las cookies, en función de su permanencia, pueden dividirse en cookies de sesión o permanentes. Las que expiran cuando el usuario cierra el navegador. Las que expiran en función de cuando se cumpla el objetivo para el que sirven (por ejemplo, para que el usuario se mantenga identificado en los servicios de Sefarin Martínez Martínez) o bien cuando se borran manualmente. Nombre 	Tipo 	Caducidad 	Finalidad Clase __utma 	De Terceros (Google Analytics) 	2 años 	Se usa para distinguir usuarios y sesiones. 	No Exenta __utmb 	De Terceros (Google Analytics) 	30 minutos 	Se usa para determinar nuevas sesiones o visitas 	No Exenta __utmc 	De Terceros (Google Analytics) 	Al finalizar la sesión 	Se configura para su uso con Urchin 	No Exenta __utmz 	De Terceros (Google Analytics) 	6 meses 	Almacena el origen o la campaña que explica cómo el usuario ha llegado hasta la página web 	No Exenta":"The cookies used on our website are session and third-party cookies, and allow us to store and access information related to the language, the type of browser used, and other general characteristics predefined by the user, as well as to follow and analyze the activity. carried out, in order to introduce improvements and provide our services in a more efficient and personalized way. Cookies, depending on their permanence, can be divided into session or permanent cookies. Those that expire when the user closes the browser. Those that expire depending on when the purpose for which they serve is fulfilled (for example, so that the user remains identified in the services of Sefarin Martínez Martínez) or when they are manually deleted. Name Type Expiration Purpose className __utma De Terceros (Google Analytics) 2 years Used to distinguish users and sessions. Not Exempt  __utmb From Third Parties (Google Analytics) 30 minutes Used to determine new sessions or visits Not Exempt __utmc From Third Parties (Google Analytics) At the end of the session It is configured for use with Urchin Not Exempt __utmz From Third Parties (Google Analytics) 6 months Stores the origin or the campaign that explains how the user has reached the Non-Exempt web page"}</p>
                        </li>
                        <p>{lenguague==='es'?"Adicionalmente, en función de su objetivo, las cookies pueden clasificarse de la siguiente forma:":"Additionally, depending on their objective, cookies can be classNameified as follows:"}</p>
                        <li>
                            <h3>{lenguague==='es'?"Cookies de rendimiento":"Performance cookies"}</h3>
                            <p>{lenguague==='es'?"Este tipo de Cookie recuerda sus preferencias para las herramientas que se encuentran en los servicios, por lo que no tiene que volver a configurar el servicio cada vez que usted visita. A modo de ejemplo, en esta tipología se incluyen: Ajustes de volumen de reproductores de vídeo o sonido. Las velocidades de transmisión de vídeo que sean compatibles con su navegador. Los objetos guardados en el “carrito de la compra” en los servicios de e-commerce tales como tiendas.":"This type of Cookie remembers your preferences for the tools found in the services, so you do not have to reconfigure the service each time you visit. As an example, this typology includes: Volume settings for video or sound players. The video transmission speeds that are compatible with your browser. The objects stored in the 'shopping cart' in e-commerce services such as stores."}</p>
                        </li>
                        <li>
                            <h3>{lenguague==='es'?"Cookies de geo-localización":"Geo-location cookies"}</h3>
                            <p>{lenguague==='es'?"Estas cookies son utilizadas para averiguar en qué país se encuentra cuando se solicita un servicio. Esta cookie es totalmente anónima, y sólo se utiliza para ayudar a orientar el contenido a su ubicación.":"These cookies are used to find out which country you are in when a service is requested. This cookie is completely anonymous, and is only used to help guide content to your location."}</p>
                        </li>
                        <li>
                            <h3>{lenguague==='es'?"Cookies de registro":"Log cookies"}</h3>
                            <p>{lenguague==='es'?"Las cookies de registro se generan una vez que el usuario se ha registrado o posteriormente ha abierto su sesión, y se utilizan para identificarle en los servicios con los siguientes objetivos: Mantener al usuario identificado de forma que, si cierra un servicio, el navegador o el ordenador y en otro momento u otro día vuelve a entrar en dicho servicio, seguirá identificado, facilitando así su navegación sin tener que volver a identificarse. Esta funcionalidad se puede suprimir si el usuario pulsa la funcionalidad [cerrar sesión], de forma que esta cookie se elimina y la próxima vez que entre en el servicio el usuario tendrá que iniciar sesión para estar identificado. Comprobar si el usuario está autorizado para acceder a ciertos servicios, por ejemplo, para participar en un concurso. Adicionalmente, algunos servicios pueden utilizar conectores con redes sociales tales como Facebook o Twitter. Cuando el usuario se registra en un servicio con credenciales de una red social, autoriza a la red social a guardar una Cookie persistente que recuerda su identidad y le garantiza acceso a los servicios hasta que expira. El usuario puede borrar esta Cookie y revocar el acceso a los servicios mediante redes sociales actualizando sus preferencias en la red social que específica.":"Registration cookies are generated once the user has registered or subsequently opened his session, and are used to identify him in the services with the following objectives: Keeping the user identified in such a way that, if he closes a service, the browser or the computer and at another time or another day he re-enters said service, he will remain identified, thus facilitating his navigation without having to re-identify himself. This functionality can be suppressed if the user presses the [close session] functionality, so that this cookie is eliminated and the next time the user enters the service, the user will have to log in to be identified. Check if the user is authorized to access certain services, for example, to participate in a contest. Additionally, some services may use connectors with social networks such as Facebook or Twitter. When the user registers for a service with credentials from a social network, they authorize the social network to save a persistent Cookie that remembers their identity and guarantees access to the services until it expires. The user can delete this Cookie and revoke access to services through social networks by updating their preferences in the specific social network."}</p>
                        </li>
                        <li>
                            <h3>{lenguague==='es'?"Cookies de analíticas":"Analytics cookies"}</h3>
                            <p>{lenguague==='es'?"Cada vez que un usuario visita un servicio, una herramienta de un proveedor externo genera una cookie analítica en el ordenador del usuario. Esta cookie que sólo se genera en la visita, servirá en próximas visitas a los servicios de Sefarin Martínez Martínez para identificar de forma anónima al visitante. Los objetivos principales que se persiguen son: Permitir la identificación anónima de los usuarios navegantes a través de la cookie (identifica navegadores y dispositivos, no personas) y por lo tanto la contabilización aproximada del número de visitantes y su tendencia en el tiempo. Identificar de forma anónima los contenidos más visitados y por lo tanto más atractivos para los usuarios Saber si el usuario que está accediendo es nuevo o repite visita. Importante: Salvo que el usuario decida registrarse en un servicio de Sefarin Martínez Martínez, la cookie nunca irá asociada a ningún dato de carácter personal que pueda identificarle. Dichas cookies sólo serán utilizadas con propósitos estadísticos que ayuden a la optimización de la experiencia de los usuarios en el sitio.":"Every time a user visits a service, a tool from an external provider generates an analytical cookie on the user's computer. This cookie, which is only generated during the visit, will serve in future visits to the services of Sefarin Martínez Martínez to identify the visitor anonymously. The main objectives pursued are: Allow anonymous identification of browsing users through the cookie (identifies browsers and devices, not people) and therefore the approximate count of the number of visitors and their trend over time. Anonymously identify the most visited content and therefore the most attractive to users. Know if the user who is accessing is new or repeats visit. Important: Unless the user decides to register for a Sefarin Martínez Martínez service, the cookie will never be associated with any personal data that can identify them. These cookies will only be used for statistical purposes that help to optimize the user experience on the site."}</p>
                        </li>
                        <li>
                            <h3>{lenguague==='es'?"Cookies de publicidad":"Advertising cookies"}</h3>
                            <p>{lenguague==='es'?"Este tipo de cookies permiten ampliar la información de los anuncios mostrados a cada usuario anónimo en los servicios de Sefarin Martínez Martínez. Entre otros, se almacena la duración o frecuencia de visualización de posiciones publicitarias, la interacción con las mismas, o los patrones de navegación y/o comportamientos del usuario ya que ayudan a conformar un perfil de interés publicitario. De este modo, permiten ofrecer publicidad afín a los intereses del usuario.":"This type of cookies allows you to expand the information of the advertisements displayed to each anonymous user in the services of Sefarin Martínez Martínez. Among others, the duration or frequency of viewing advertising positions, the interaction with them, or the browsing patterns and / or user behaviors are stored as they help to form a profile of advertising interest. In this way, they allow to offer advertising related to the interests of the user."}</p>
                        </li>
                        <li>
                            <h3>{lenguague==='es'?"Cookies publicitarias de terceros":"Third-party advertising cookies"}</h3>
                            <p>{lenguague==='es'?"Además de la publicidad gestionada por las webs de Serafin Martínez Martínez en sus servicios, las webs de Sefarin Martínez Martínez ofrecen a sus anunciantes la opción de servir anuncios a través de terceros (“Ad-Servers”). De este modo, estos terceros pueden almacenar cookies enviadas desde los servicios de Sefarin Martínez Martínez procedentes de los navegadores de los usuarios, así como acceder a los datos que en ellas se guardan. Las empresas que generan estas cookies tienen sus propias políticas de privacidad. En la actualidad, las webs de Sefarin Martínez Martínez utilizan la plataforma Doubleclick (Google) para gestionar estos servicios. Para más información, acuda a http://www.google.es/policies/privacy/ads/#toc-doubleclick y a http://www.google.es/policies/privacy/ads/.":"In addition to the advertising managed by the Serafin Martínez Martínez websites in their services, the Sefarin Martínez Martínez websites offer their advertisers the option of serving advertisements through third parties ('Ad-Servers'). In this way, these third parties can store cookies sent from the services of Sefarin Martínez Martínez from the users' browsers, as well as access the data stored in them. The companies that generate these cookies have their own privacy policies. Currently, the Sefarin Martínez Martínez websites use the Doubleclick (Google) platform to manage these services. For more information, go to  http://www.google.es/policies/privacy/ads/#toc-doubleclick and http://www.google.es/policies/privacy/ads/."}</p>
                        </li>
                        <li>
                            <h3>{lenguague==='es'?"¿Cómo puedo deshabilitar las cookies en mi navegador?":"How can I disable cookies in my browser?"}</h3>
                            <p>{lenguague==='es'?"Se pueden configurar los diferentes navegadores para avisar al usuario de la recepción de cookies y, si se desea, impedir su instalación en el equipo. Asimismo, el usuario puede revisar en su navegador qué cookies tiene instaladas y cuál es el plazo de caducidad de las mismas, pudiendo eliminarlas.Para ampliar esta información consulte las instrucciones y manuales de su navegador: Para más información sobre la administración de las cookies en Google Chrome: https://support.google.com/chrome/answer/95647?hl=es Para más información sobre la administración de las cookies en Internet Explorer: http://windows.microsoft.com/es-es/windows-vista/cookies-frequently-asked-questions Para más información sobre la administración de las cookies en Mozilla Firefox: http://support.mozilla.org/es/kb/habilitar-y-deshabilitar-cookies-que-los-sitios-we Para más información sobre la administración de las cookies en Safari: http://www.apple.com/es/privacy/use-of-cookies/ Para más información sobre la administración de las cookies en Opera: http://help.opera.com/Windows/11.50/es-ES/cookies.html Si desea dejar de ser seguido por Google Analytics visite: http://tools.google.com/dlpage/gaoptout.":"The different browsers can be configured to notify the user of the receipt  of cookies and, if desired, prevent their installation on the computer. Likewise, the user can check in his browser which cookies he has installed and what is the expiration period of the same, being able to eliminate them. To expand this information, consult the instructions and manuals of your browser: For more information on the administration of cookies in Google Chrome: https://support.google.com/chrome/answer/95647?hl=es For more information on managing cookies in Internet Explorer: http://windows.microsoft.com/es-es/windows-vista/cookies-frequently-asked-questions For more information on the administration of cookies in Mozilla Firefox: http://support.mozilla.org/es/kb/habilitar-y-deshabilitar-cookies-que-los-sitios-we For more information on the administration of cookies in Safari: http://www.apple.com/es/privacy/use-of-cookies/ For more information on managing cookies in Opera: http://help.opera.com/Windows/11.50/es-ES/cookies.html If you want to stop being followed by Google Analytics visit: http://tools.google.com/dlpage/gaoptout."}</p>
                        </li>
                        <li>
                            <h3>{lenguague==='es'?"Para saber más sobre las cookies":"To know more about cookies"}</h3>
                            <p>{lenguague==='es'?"Puede obtener más información sobre la publicidad online basada en el comportamiento y la privacidad online en el siguiente enlace: http://www.youronlinechoices.com/es/ Protección de datos de Google Analytics: http://www.google.com/analytics/learn/privacy.html Cómo usa Google Analytics las cookies: https://developers.google.com/analytics/devguides/collection/analyticsjs/cookie-usage?hl=es#analyticsjs.":"You can obtain more information about online advertising based on behavior and online privacy at the following link: http://www.youronlinechoices.com/es/ Google Analytics data protection: http://www.google.com/analytics/learn/privacy.html How Google Analytics uses cookies: https://developers.google.com/analytics/devguides/collection/analyticsjs/cookie-usage?hl=es#analyticsjs"}</p>
                        </li>
                        <li>
                            <h3>{lenguague==='es'?"Actualizaciones y cambios en la política de privacidad/cookies":"Updates and changes in the privacy policy / cookies"}</h3>
                            <p>{lenguague==='es'?"Las webs de Serafin Martínez Martínez pueden modificar esta Política de Cookies en función de exigencias legislativas, reglamentarias, o con la finalidad de adaptar dicha política a las instrucciones dictadas por la Agencia Española de Protección de Datos, por ello se aconseja a los usuarios que la visiten periódicamente. Cuando se produzcan cambios significativos en esta Política de Cookies, estos se comunicarán a los usuarios bien mediante la web o a través de correo electrónico a los usuarios registrados.":"The Serafin Martínez Martínez websites may modify this Cookies Policy based on legislative and regulatory requirements, or in order to adapt said policy to the instructions issued by the Spanish Data Protection Agency, therefore users are advised that it visit periodically. When there are significant changes in this Cookies Policy, these will be communicated to users either through the web or through email to registered users."}</p>
                        </li>
                    </ul>
                </section>
        </div>
    )
} 